"""
Read the GraphQL ops captured by parse_har.py and emit src/queries.py
containing each query we need as a Python string constant.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OPS_DIR = ROOT / "data" / "graphql_ops"
OUT = ROOT / "src" / "queries.py"

# Map: constant name -> input JSON file (root__qhash.json)
WANTED = {
    "CONVERSATION_LIST":              "node__d2d39da7.json",
    "CONVERSATION_LIST_PAGINATION":   "node__f22928bc.json",
    "LOG_DETAIL":                     "session__0db0f553.json",
    "LOG_TRACES":                     "botByID__accc69a6.json",
    "LOG_MONITOR_RESULTS":            "botByID__c215a52d.json",
    "JOURNEYS_LIST":                  "workspaceVersionByID__12c0f923.json",
    "JOURNEY_DETAIL":                 "workspaceVersionByID__010131cb.json",
    "TOOLS_LIST":                     "workspaceVersionByID__095eeede.json",
    "KNOWLEDGE_SOURCES":              "allKnowledgeSources__44f62a6a.json",
    "KB_ARTICLES_LIST":               "knowledgeSourceByID__48564380.json",
    "KB_ARTICLE_DETAIL":              "knowledgeSourceByID__da90f332.json",
}


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '"""GraphQL query strings extracted from the Sierra HAR capture."""',
        "# AUTO-GENERATED by scripts/extract_queries.py — do not hand-edit.",
        "",
    ]
    for const, fname in WANTED.items():
        path = OPS_DIR / fname
        if not path.exists():
            print(f"MISSING: {fname}")
            continue
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        query = data["query"]
        lines.append(f"{const} = r'''{query}'''")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} with {len(WANTED)} queries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
