"""GraphQL query strings extracted from the Sierra HAR capture."""
# AUTO-GENERATED by scripts/extract_queries.py — do not hand-edit.

CONVERSATION_LIST = r'''query conversationListQuery(
  $agentId: ID!
  $search: String
  $timeRange: BotLogsTimeRange
  $tags: [String!]
  $journeys: [String!]
  $reviewStatuses: [LogReviewStatus!]
  $releases: [String!]
  $targets: [String!]
  $channels: [String!]
  $containsUserMessages: Boolean!
  $filterQuery: String
) {
  node(id: $agentId) {
    __typename
    ... on Bot {
      id
      ...conversationListFragment_3jsdhk
    }
    id
  }
}

fragment conversationListConversationFragment_40zwac on Log {
  id
  timestamp
  messageCount
  messageCountWithGreeting
  mcpTurnCount
  mcpConversationTitle
  duration
  tags
  device
  releaseTarget
  reviewStatus
  searchHighlights(searchQuery: $search)
  firstUserMessage {
    text
  }
}

fragment conversationListFragment_3jsdhk on Bot {
  logs(search: $search, timeRange: $timeRange, tags: $tags, journeys: $journeys, reviewStatuses: $reviewStatuses, releases: $releases, targets: $targets, channels: $channels, containsUserMessages: $containsUserMessages, filterQuery: $filterQuery, first: 50) {
    edges {
      node {
        id
        ...conversationListConversationFragment_40zwac
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
  id
}
'''

CONVERSATION_LIST_PAGINATION = r'''query conversationListPaginationQuery(
  $channels: [String!]
  $containsUserMessages: Boolean!
  $count: Int = 50
  $cursor: String
  $filterQuery: String
  $journeys: [String!]
  $releases: [String!]
  $reviewStatuses: [LogReviewStatus!]
  $search: String
  $tags: [String!]
  $targets: [String!]
  $timeRange: BotLogsTimeRange
  $id: ID!
) {
  node(id: $id) {
    __typename
    ...conversationListFragment_qRtBH
    id
  }
}

fragment conversationListConversationFragment_40zwac on Log {
  id
  timestamp
  messageCount
  messageCountWithGreeting
  mcpTurnCount
  mcpConversationTitle
  duration
  tags
  device
  releaseTarget
  reviewStatus
  searchHighlights(searchQuery: $search)
  firstUserMessage {
    text
  }
}

fragment conversationListFragment_qRtBH on Bot {
  logs(search: $search, timeRange: $timeRange, tags: $tags, journeys: $journeys, reviewStatuses: $reviewStatuses, releases: $releases, targets: $targets, channels: $channels, containsUserMessages: $containsUserMessages, filterQuery: $filterQuery, after: $cursor, first: $count) {
    edges {
      node {
        id
        ...conversationListConversationFragment_40zwac
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
  id
}
'''

LOG_DETAIL = r'''query useLogQuery(
  $agentId: String!
  $logId: String!
  $search: String
  $piiRevealReason: String
  $tracePiiRevealReason: String
  $translate: Boolean = false
  $includeMonitorResults: Boolean = false
  $includeDeveloperTags: Boolean = false
  $includeEmployeeTags: Boolean = false
) {
  session {
    org {
      id
    }
  }
  botByID(id: $agentId) {
    id
    logByID(id: $logId) {
      id
      externalConversationKey
      externalChatInfo {
        externalChatSystem
        externalConversationId
        externalConversationUrl
      }
      contactCenterConnection {
        id
      }
      timestamp
      tags
      journeyIds
      developerTags @include(if: $includeDeveloperTags)
      employeeTags @include(if: $includeEmployeeTags)
      device
      locale
      searchHighlights(searchQuery: $search)
      getMonitorReportResult @include(if: $includeMonitorResults) {
        overallQualityScore
        qualityCategoryResults {
          category
          score
        }
        sentimentResults
      }
      release {
        hash
        target
        name
        hotSwapForDev
        brand {
          greetingMessage
          errorMessage
          inactivityMessage
          agentTransferWaitingMessage
          agentJoinedMessage
          agentLeftMessage
          conversationEndedMessage
          canRenderMessageImages
          uiStrings
        }
        id
      }
      customFields {
        name
        value
        tag
      }
      personalIdentifiers(piiRevealReason: $piiRevealReason) {
        type
        label
        customTypeName
        value
        endUserId
      }
      telephonyMetadata {
        isOutbound
        twilio {
          callType
        }
        genesys {
          genesysOrgId
          genesysConversationId
        }
      }
      outboundCallRecord {
        id
      }
      reviewStatus
      reviewedByPerson
      isTransferred: matchesExpression(name: "transfer")
      issues {
        issue {
          id
          name
          number
          severity
          category
          status
        }
        logEntryIds
      }
      batches {
        id
        name
      }
      traceEvents(piiRevealReason: $tracePiiRevealReason) {
        ...tracesEventFragment
      }
      audioInfo {
        sessionDurations
        recordingDisabled
      }
      voiceSettings {
        personaName
        transcriptionOptions {
          providerId
          model
          locale
          keywords
        }
        synthesisOptions {
          providerId
          model
          voiceName
          voiceDescription
          guidance
          stability
          speakingRate
          similarityBoost
          flushMaxChunks
          useSpeakerBoost
          useAlignmentInMultiContext
          useCoveringSequence
        }
      }
      entries(piiRevealReason: $piiRevealReason) {
        id
        timestampMs
        event {
          __typename
          ... on LogEntryBotFeedback {
            __typename
            feedback
            sentiment
          }
          ... on LogEntryMessage {
            __typename
            author
            authorDisplayName
            text
            translatedText @include(if: $translate)
            translatedInterruptedText @include(if: $translate)
            isEnglish
            attachments {
              type
              data
            }
            audioInfo {
              sessionIndex
              startInCallTime
              endInCallTime
            }
            wasInterrupted
            interruptedText
            userInterruptionMetadata {
              ignoredInterruption
            }
            synthesisText
            transcriptionMetadata {
              words {
                word
                index
                speakerId
                wordConfidence
              }
              messageConfidence
              piiRedactionRequestId
            }
            isDtmf
          }
          ... on LogEntryAgentTransfer {
            __typename
            isSynchronous
            isContactCenter
            data {
              key
              value
            }
            transferData {
              phone {
                phoneNumber
                action
                sendDigits
                callerId
              }
              sip {
                endpoint
                customHeaders {
                  key
                  value
                }
                username
                password
              }
              twilioApp {
                appId
                customParams {
                  key
                  value
                }
              }
              hangup {
                customParams {
                  key
                  value
                }
              }
            }
          }
          ... on LogEntryEndConversation {
            __typename
            reason
            data {
              key
              value
            }
          }
          ... on LogEntryCallDisconnect {
            __typename
            reason
          }
          ... on LogEntryRequestEndConversation {
            __typename
            reason
          }
          ... on LogEntryInternalFeedback {
            __typename
            text
            type
            componentHierarchy
          }
          ... on LogEntryInternalLog {
            __typename
            message
            level
            error
            showAgentLog
            extra
          }
          ... on LogEntryAgentTagLog {
            __typename
            tags
          }
          ... on LogEntryUserSurvey {
            __typename
            actionType
            stars
          }
          ... on LogEntryUpdateMemory {
            __typename
            variables {
              name
              value
            }
            secrets
          }
          ... on LogEntryToolInvocation {
            __typename
            name
            arguments
          }
          ... on LogEntryToolResponse {
            __typename
            name
            response
            knowledge
          }
          ... on LogEntryEmbeddedLink {
            __typename
            link
            label
          }
          ... on LogEntryHumanAgentParticipation {
            __typename
            participationType
            displayName
          }
          ... on LogEntryKnowledgeCitations {
            __typename
            query
            results {
              id
              sourceId
              title
              url
              urlHash
              isInternalUrl
              chunkIds
              chunkingStrategy
            }
            version
          }
          ... on LogEntryContentAccess {
            __typename
            entryName
            message
            recordId
            recordJson
          }
          ... on LogEntryUninterruptibleSection {
            __typename
            start
          }
          ... on LogEntryAgentEvent {
            __typename
            event
            propertiesJson
          }
          ... on LogEntryInitiatePay {
            __typename
            captureMethod
            params {
              __typename
              ... on VoiceInlineCapturePayParams {
                __typename
                description
              }
              ... on ChatIframeCapturePayParams {
                __typename
                prompt
                componentName
                customParams {
                  key
                  value
                }
                connector
              }
            }
          }
          ... on LogEntryInitiatePayResult {
            __typename
            secureModeSuccess
            callReference
            errorMessage
          }
          ... on LogEntryPaymentCaptureStatus {
            __typename
            captureType
            paymentCaptureStatus: status {
              __typename
              ... on InvalidPaymentCaptureStatus {
                __typename
              }
              ... on VoiceExternalPaymentCaptureStatus {
                __typename
                callReference
                digitsCaptured
                panState
                cvcState
                panLength
                cvcLength
                expectedPanLength
                expectedCvvLength
                luhnCheckPassed
                complete
                callState
                securePaymentModeState
                validationState
                panValidationState
                cvcValidationState
              }
              ... on VoiceInlinePaymentCaptureStatus {
                __typename
                result
                profileId
                paymentToken
                paymentConfirmationCode
                paymentMethod
                maskedPaymentCardNumber
                paymentCardType
                expirationDate
                maskedBankAccountNumber
                bankRoutingNumber
                bankAccountType
                paymentError
                payErrorCode
                connectorError
                customStatus {
                  key
                  value
                }
              }
              ... on ChatIframePaymentCaptureStatus {
                __typename
                customStatus {
                  key
                  value
                }
                connector
                connectorStatus {
                  __typename
                  ... on GenericChatIframeCaptureStatus {
                    __typename
                    status
                    errorMessage
                  }
                  ... on StripeChatIframeCaptureStatus {
                    __typename
                    errorMessage
                    setupIntent {
                      status
                      paymentMethodId
                      lastSetupError {
                        key
                        value
                      }
                    }
                  }
                  ... on Shift4ChatIframeCaptureStatus {
                    __typename
                    status
                    errorMessage
                    token
                  }
                }
              }
            }
          }
          ... on LogEntryCollectSensitiveField {
            __typename
            fieldType
            connector
            prompt
            timeout
            numDigits
            finishOnKey
            customParams {
              key
              value
            }
          }
          ... on LogEntrySensitiveFieldResult {
            __typename
            sensitiveFieldResult {
              fieldType
              status
              errorMessage
            }
          }
          ... on LogEntrySecureCollectionPrompt {
            __typename
            collectionType
            fieldLabel
            text
          }
          ... on LogEntryRequestFullRedactionMode {
            __typename
          }
          ... on LogEntryRequestFullRedactionModeComplete {
            __typename
          }
          ... on LogEntryFullRedactionModeStart {
            __typename
          }
          ... on LogEntryFullRedactionModeEnd {
            __typename
          }
          ... on LogEntrySetPersonalIdentifier {
            __typename
            type
            hashedValue
            endUserId
            identitySource
            authMethod
            linkIdentity
          }
          ... on LogEntryAppTask {
            __typename
            taskId
          }
        }
        isDebug
      }
    }
  }
}

fragment tracesEventFragment on AgentTraceEvent {
  timestampMs
  chatLogEntryID
  agentChatLogEntryIDs
  type
  redactionMode
  logMessage {
    message
    timestamp
  }
  llmChat {
    id
    purpose
    usage
    componentHierarchy
    request
    async
    functions {
      name
      description
      parameters
    }
    messages {
      text
      role
      name
    }
    jsonSchema
    sdkSpanTraceId
  }
  llmChatResponse {
    requestID
    retries
    response
    responseErr
    message {
      text
      role
    }
    functionCall {
      name
      arguments
    }
    latencies {
      timeToFirstText
      timeToLastText
      timeToFirstAudio
      timeToLastAudio
    }
    metadata {
      underlyingRequestStats {
        startTimeMs
        firstTokenTimeMs
        endTimeMs
        chosen
        provider
        model
      }
      hedgingDelayMs
      modelSelectionStats {
        selectedModel
        candidateModels
        strategy
        modelHealthStats {
          modelId
          providerStats {
            provider
            healthScore
            sampleCount
            rateLimitingScore
          }
        }
      }
      retryAttempts {
        model
        responseText
        responseLatencyMs
      }
    }
    sdkSpanTraceId
    cached
    inputTokens
    cachedInputTokens
    outputTokens
  }
  fetch {
    request {
      url
      method
      headers
      body
      timeout
      isBackchannel
    }
    sdkSpanTraceId
    response {
      status
      body
      responseTime
      contentLength
    }
    responseErr
    responseErrTime
    defaultLog
    async
    prepareDuration
  }
  task {
    id
    taskId
    input
    output
    usage
    taskTags
  }
  sleep {
    duration
    label
    async
  }
  knowledgeSearch {
    id
    duration
  }
  conversationTurn {
    type
    start_time
    end_time
    duration_ms
    properties_json
    response_traces {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    last_response {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    first_full_response {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    first_relevant_grounded_response {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    span_traces {
      name
      type
      start_time
      end_time
      duration_ms
      span_trace_id
      error
      children {
        name
        type
        start_time
        end_time
        duration_ms
        span_trace_id
        properties_json
        error
      }
      properties_json
    }
  }
  voiceSidecar {
    entrypoint
    start_time
    end_time
    duration_ms
    logs {
      timestamp
      message
      level
    }
  }
  mcp {
    sdkSpanTraceId
    http {
      request {
        method
        url
        headersJson
      }
      response {
        statusCode
        headersJson
      }
      failure
      durationNs
    }
    jsonRpc {
      direction
      idJson
      request {
        method
        paramsJson
      }
      result {
        resultJson
      }
      error {
        code
        message
        dataJson
      }
      durationNs
    }
    jsonRpcNotification {
      direction
      method
      paramsJson
    }
  }
  agentMemory {
    operation
    state
    reasoningId
    paramsJson
    resultJson
    entityId
  }
  identity {
    identifierType
    endUserID
    identitySource
    authMethod
    isMidConversationUpgrade
    customTypeName
  }
}
'''

LOG_TRACES = r'''query onDemandRedactedTracesQuery(
  $agentId: String!
  $logId: String!
  $allowReredaction: Boolean = false
) {
  botByID(id: $agentId) {
    logByID(id: $logId) {
      traceEvents(allowReredaction: $allowReredaction) {
        ...tracesEventFragment
      }
      id
    }
    id
  }
}

fragment tracesEventFragment on AgentTraceEvent {
  timestampMs
  chatLogEntryID
  agentChatLogEntryIDs
  type
  redactionMode
  logMessage {
    message
    timestamp
  }
  llmChat {
    id
    purpose
    usage
    componentHierarchy
    request
    async
    functions {
      name
      description
      parameters
    }
    messages {
      text
      role
      name
    }
    jsonSchema
    sdkSpanTraceId
  }
  llmChatResponse {
    requestID
    retries
    response
    responseErr
    message {
      text
      role
    }
    functionCall {
      name
      arguments
    }
    latencies {
      timeToFirstText
      timeToLastText
      timeToFirstAudio
      timeToLastAudio
    }
    metadata {
      underlyingRequestStats {
        startTimeMs
        firstTokenTimeMs
        endTimeMs
        chosen
        provider
        model
      }
      hedgingDelayMs
      modelSelectionStats {
        selectedModel
        candidateModels
        strategy
        modelHealthStats {
          modelId
          providerStats {
            provider
            healthScore
            sampleCount
            rateLimitingScore
          }
        }
      }
      retryAttempts {
        model
        responseText
        responseLatencyMs
      }
    }
    sdkSpanTraceId
    cached
    inputTokens
    cachedInputTokens
    outputTokens
  }
  fetch {
    request {
      url
      method
      headers
      body
      timeout
      isBackchannel
    }
    sdkSpanTraceId
    response {
      status
      body
      responseTime
      contentLength
    }
    responseErr
    responseErrTime
    defaultLog
    async
    prepareDuration
  }
  task {
    id
    taskId
    input
    output
    usage
    taskTags
  }
  sleep {
    duration
    label
    async
  }
  knowledgeSearch {
    id
    duration
  }
  conversationTurn {
    type
    start_time
    end_time
    duration_ms
    properties_json
    response_traces {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    last_response {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    first_full_response {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    first_relevant_grounded_response {
      first_token_time
      first_sentence_time
      done_time
      duration_ms
      type
      properties_json
    }
    span_traces {
      name
      type
      start_time
      end_time
      duration_ms
      span_trace_id
      error
      children {
        name
        type
        start_time
        end_time
        duration_ms
        span_trace_id
        properties_json
        error
      }
      properties_json
    }
  }
  voiceSidecar {
    entrypoint
    start_time
    end_time
    duration_ms
    logs {
      timestamp
      message
      level
    }
  }
  mcp {
    sdkSpanTraceId
    http {
      request {
        method
        url
        headersJson
      }
      response {
        statusCode
        headersJson
      }
      failure
      durationNs
    }
    jsonRpc {
      direction
      idJson
      request {
        method
        paramsJson
      }
      result {
        resultJson
      }
      error {
        code
        message
        dataJson
      }
      durationNs
    }
    jsonRpcNotification {
      direction
      method
      paramsJson
    }
  }
  agentMemory {
    operation
    state
    reasoningId
    paramsJson
    resultJson
    entityId
  }
  identity {
    identifierType
    endUserID
    identitySource
    authMethod
    isMidConversationUpgrade
    customTypeName
  }
}
'''

LOG_MONITOR_RESULTS = r'''query useLogSystemMonitorResultsQuery(
  $agentId: String!
  $logId: String!
) {
  botByID(id: $agentId) {
    logByID(id: $logId) {
      getSystemMonitorResults {
        monitorId
        slug
        name
        detected
      }
      id
    }
    id
  }
}
'''

JOURNEYS_LIST = r'''query useJourneysWorkspaceVersionQuery(
  $workspaceVersionId: String!
  $enabled: Boolean!
) {
  workspaceVersionByID(id: $workspaceVersionId) @include(if: $enabled) {
    ...useJourneysWorkspaceVersionFragment
    id
  }
}

fragment useJourneysJourneyFragment on Journey {
  id
  botId
  name
  status
  publishedJourneyVersion {
    id
    description
    criteria
    editorStateJson
    tags
  }
  editingJourneyVersion {
    id
    description
    criteria
    editorStateJson
    tags
    createdAt
    updatedAt
    creator {
      name
      id
    }
    updatedBy {
      name
      id
    }
  }
}

fragment useJourneysWorkspaceVersionFragment on WorkspaceVersion {
  journeys(first: 50) {
    edges {
      node {
        ...useJourneysJourneyFragment
        id
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
  id
}
'''

JOURNEY_DETAIL = r'''query useJourneyWorkspaceVersionQuery(
  $workspaceVersionId: String!
  $journeyId: ID!
  $shouldFetchSnapshot: Boolean!
) {
  workspaceVersionByID(id: $workspaceVersionId) {
    journeyByID(id: $journeyId) {
      ...useJourneyJourneyFragment_3olEdB
      id
    }
    id
  }
}

fragment useJourneyConflictingJourneyVersionFragment on JourneyVersion {
  id
  editorStateJson
  updatedBy {
    name
    id
  }
}

fragment useJourneyEditingJourneyVersionFragment on JourneyVersion {
  id
  description
  criteria
  editorStateJson
  status
  createdAt
  updatedAt
  publishedAt
  tags
  name
  enabled
  tools {
    id
    name
    description
    type
    paramsJson
  }
  creator {
    email
    id
  }
  updatedBy {
    email
    name
    id
  }
  liveAssistOnly
}

fragment useJourneyJourneyFragment_3olEdB on Journey {
  id
  botId
  name
  status
  liveAssistOnly
  publishedJourneyVersion {
    id
    description
    criteria
    editorStateJson
    createdAt
    publishedAt
    tags
  }
  editingJourneyVersion {
    ...useJourneyEditingJourneyVersionFragment
    ...useJourneyVersionMentionEntitiesFragment
    id
  }
  workspaceMergeConflicts {
    theirs {
      ...useJourneyConflictingJourneyVersionFragment
      id
    }
    base {
      ...useJourneyConflictingJourneyVersionFragment
      id
    }
    updatedOursEditorJSON
    conflictingTheirsNodeOperations {
      type
      nodeUUID
      childUUID
    }
  }
  latestSnapshotJourneyVersion @include(if: $shouldFetchSnapshot) {
    ...useJourneyLatestSnapshot
    id
  }
}

fragment useJourneyLatestSnapshot on JourneyVersion {
  id
  updatedAt
  editorStateJson
}

fragment useJourneyVersionMentionEntitiesFragment on JourneyVersion {
  mentionedEntities {
    tools {
      id
      name
      description
      createdAt
      updatedAt
    }
    builtInToolIds
    readArticleTools {
      name
      content
      knowledgeSourceId
      urlHash
    }
    searchKnowledgeSourceTools {
      name
      knowledgeSourceId
    }
    contentRecordValues {
      contentDatabaseId
      contentRecordId
      contentEntryName
      contentValueQuery
      value
    }
    embeddedJourneys {
      journeyId
      journeyName
    }
    integrationTools {
      id
      name
      integrationId
    }
  }
}
'''

TOOLS_LIST = r'''query useToolsAsyncWorkspaceVersionQuery(
  $workspaceVersionId: String!
) {
  workspaceVersionByID(id: $workspaceVersionId) {
    journeyTools(first: 1000) {
      edges {
        node {
          id
          name
          description
          type
        }
      }
    }
    id
  }
}
'''

KNOWLEDGE_SOURCES = r'''query knowledgeSourcesQuery(
  $botId: ID
  $workspaceId: String!
  $workspaceVersionId: String!
  $useWorkspaceKnowledgeSources: Boolean!
) {
  allKnowledgeSources(botId: $botId) @skip(if: $useWorkspaceKnowledgeSources) {
    id
    botId
    name
    type
    ...sourcesPanel_knowledgeSources
  }
  workspaceKnowledgeSources(workspaceId: $workspaceId, workspaceVersionId: $workspaceVersionId) @include(if: $useWorkspaceKnowledgeSources) {
    id
    botId
    name
    type
    ...sourcesPanel_knowledgeSources
  }
}

fragment sourcesPanel_knowledgeSources on KnowledgeSource {
  id
  orgId
  botId
  name
  articleCount
  unreviewedDraftCount
  snapshots(first: 5) {
    edges {
      node {
        id
        indexingStatus
      }
    }
  }
  originConfig {
    isConfigured
    agent {
      workspaceId
    }
    integration {
      integrationHandle
    }
    firecrawl {
      url
    }
    zendesk {
      subDomain
    }
    reamaze {
      brandName
    }
    aiResearch {
      additionalContext
      maxArticles
    }
  }
  importTasks(first: 1) {
    edges {
      node {
        id
        status
        createdTime
      }
    }
  }
  isDraft
  crawlingStatus
  type
}
'''

KB_ARTICLES_LIST = r'''query useKnowledgeSourceArticlesQuery(
  $sourceId: String!
  $workspaceId: String!
  $workspaceVersionId: String!
  $useWorkspaceKnowledgeArticles: Boolean!
  $orderBy: ArticleOrderBy = UPDATED_TIME_DESC
) {
  knowledgeSourceByID(id: $sourceId) @skip(if: $useWorkspaceKnowledgeArticles) {
    ...useKnowledgeSourceArticlesFragment_7FfCv
    id
  }
  ...useKnowledgeSourceArticlesWorkspaceFragment_15ydKZ @include(if: $useWorkspaceKnowledgeArticles)
}

fragment useKnowledgeSourceArticlesFragment_7FfCv on KnowledgeSource {
  articles(first: 50, orderBy: $orderBy) {
    edges {
      node {
        id
        urlHash
        title
        updatedTime
        status
        needsReviewNotification
        partitions {
          name
          value
        }
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
  id
}

fragment useKnowledgeSourceArticlesWorkspaceFragment_15ydKZ on Query {
  workspaceKnowledgeArticles(workspaceId: $workspaceId, workspaceVersionId: $workspaceVersionId, knowledgeSourceId: $sourceId, first: 50, orderBy: $orderBy) {
    edges {
      node {
        id
        urlHash
        title
        updatedTime
        status
        needsReviewNotification
        partitions {
          name
          value
        }
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
'''

KB_ARTICLE_DETAIL = r'''query articleDetailPanelQuery(
  $sourceId: String!
  $urlHash: String!
  $workspaceId: String!
  $workspaceVersionId: String!
  $useWorkspaceKnowledgeArticle: Boolean!
) {
  knowledgeSourceByID(id: $sourceId) @skip(if: $useWorkspaceKnowledgeArticle) {
    id
    name
    orgId
    originConfig {
      isConfigured
    }
    chunkingStrategy
    type
    locale
    articleByUrlHash(urlHash: $urlHash) {
      id
      title
      content {
        body
        alternativeTitles
      }
      sourceUrl
      urlHash
      status
      needsReviewNotification
      partitions {
        name
        value
      }
      updatedTime
      sourceConversationIds
      sourceExternalConversationIds
      sourceConversations {
        id
        timestamp
      }
    }
  }
  workspaceKnowledgeSourceByID(workspaceId: $workspaceId, workspaceVersionId: $workspaceVersionId, knowledgeSourceId: $sourceId) @include(if: $useWorkspaceKnowledgeArticle) {
    id
    name
    orgId
    originConfig {
      isConfigured
    }
    chunkingStrategy
    type
    locale
  }
  workspaceKnowledgeArticleByUrlHash(workspaceId: $workspaceId, workspaceVersionId: $workspaceVersionId, knowledgeSourceId: $sourceId, urlHash: $urlHash) @include(if: $useWorkspaceKnowledgeArticle) {
    id
    title
    content {
      body
      alternativeTitles
    }
    sourceUrl
    urlHash
    status
    needsReviewNotification
    partitions {
      name
      value
    }
    updatedTime
    sourceConversationIds
    sourceExternalConversationIds
    sourceConversations {
      id
      timestamp
    }
  }
}
'''
